name: "Learning YAML"
on:
  push:
    branches:
      - dev
      - stage
jobs: 
  build_and_deploy:
    runs-on: "macos-latest"
#do necessary flutter set up
    name: "Set up Flutter"
    steps:
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@v2
      # - run: flutter run -d chrome --flavor prod -t lib/main_prod.dart
      - run: flutter doctor
      - run: flutter build apk --flavor prod -t lib/main_prod.dart
      - uses: actions/download-artifact@v3
        with:
          name: APKs
          path: build/*
      
      





