name: "Learning YAML"
on:
  push:
    branches:
      - dev
      - stage
jobs: 
  build_and_deploy:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: flutter run





