name: "Learning YAML"
on:
  push:
    branches:
      - dev
      - stage
jobs: 
  build_and_deploy:
    runs-on: "macos-latest"
#do necessary flutter set up


#do the run of the project or build apk
    steps:
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@v2
      - run: flutter run





